#!/bin/sh
#
# RUN - run CompArch test files
#
# usage:
#	RUN [ name.obj ... ] 
#
#	name.obj:	run only the listed object file(s)

program="pdp11"
list=""

#
# process command-line arguments
#

if [ $# -eq 0 ]
then

	#
	# none - test all the object files
	#
	list="$list *.obj"

else

	#
	# test only the specified object files
	#
	while [ $# -gt 0 ]
	do
		list="$list $1"
		shift
	done

fi

#
# start the testing
#
for f in $list
do

	printf "Testing %s ..." $f

	#
	# run the simulator on this object file
	#
	bn="`basename $f .obj`"
	rm -f $bn.myout $bn.diffs
	./$program $f > $bn.myout

	#
	# see if the results match exactly
	#
	cmp -s $bn.out $bn.myout
	if [ $? -eq 0 ]
	then
		printf " OK\n"
	else
		#
		# no - generate a difference listing
		#
		diff $bn.out $bn.myout > $bn.diffs
		printf " output in %s, diffs in %s\n" $bn.myout $bn.diffs
	fi

done
